// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7l3wS8x1jZ3NWCY5WDfSVfBl1mvfHGP0',
    appId: '1:1011736888409:web:53b91c237110db47971d48',
    messagingSenderId: '1011736888409',
    projectId: 'plantwise-9b5f1',
    authDomain: 'plantwise-9b5f1.firebaseapp.com',
    storageBucket: 'plantwise-9b5f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7l3wS8x1jZ3NWCY5WDfSVfBl1mvfHGP0',
    appId: '1:1011736888409:android:53b91c237110db47971d48',
    messagingSenderId: '1011736888409',
    projectId: 'plantwise-9b5f1',
    storageBucket: 'plantwise-9b5f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7l3wS8x1jZ3NWCY5WDfSVfBl1mvfHGP0',
    appId: '1:1011736888409:ios:53b91c237110db47971d48',
    messagingSenderId: '1011736888409',
    projectId: 'plantwise-9b5f1',
    storageBucket: 'plantwise-9b5f1.firebasestorage.app',
    iosBundleId: 'com.example.plantwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7l3wS8x1jZ3NWCY5WDfSVfBl1mvfHGP0',
    appId: '1:1011736888409:ios:53b91c237110db47971d48',
    messagingSenderId: '1011736888409',
    projectId: 'plantwise-9b5f1',
    storageBucket: 'plantwise-9b5f1.firebasestorage.app',
    iosBundleId: 'com.example.plantwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7l3wS8x1jZ3NWCY5WDfSVfBl1mvfHGP0',
    appId: '1:1011736888409:web:53b91c237110db47971d48',
    messagingSenderId: '1011736888409',
    projectId: 'plantwise-9b5f1',
    authDomain: 'plantwise-9b5f1.firebaseapp.com',
    storageBucket: 'plantwise-9b5f1.firebasestorage.app',
  );
}
